name: Find PR diffs

on:
    workflow_dispatch:
        inputs:
            pr:
                type: number
                description: PR to check
    issues:
        types:
        -   opened
        -   edited
        -   reopened

permissions:
    contents: read

jobs:
    fetch:
        runs-on: ubuntu-latest
        permissions:
            issues: read
        steps:
        -   uses: actions/cache/restore@v4
            id: restore-issues
            name: Restore cache
            with:
                path: downloaded/
                key: issues-dump-${{ github.run_id }}
                restore-keys: issues-dump-

        -   uses: actions/checkout@v4
            if: ${{ steps.restore-issues.outputs.cache-matched-key == '' }}
            with:
                persist-credentials: false
        -   uses: actions/setup-python@v5
            if: ${{ steps.restore-issues.outputs.cache-matched-key == '' }}
            with:
                python-version: '3.13'
        -   uses: yezz123/setup-uv@v4.1
            if: ${{ steps.restore-issues.outputs.cache-matched-key == '' }}
            with:
                uv-venv: .venv
                uv-version: 0.5.25
                uv-cache: true

        -   name: Fetch issues
            # cache-hit is false for partial matches
            if: ${{ steps.restore-issues.outputs.cache-matched-key == '' }}
            run: |
                uv run fetch
            env:
                GH_ACCESS_TOKEN: ${{ secrets.CUSTOM_GITHUB_PAT }}

        -   uses: actions/upload-artifact@v4
            with:
                name: issues-dump
                path: downloaded/
                retention-days: 1

    apply:
        runs-on: ubuntu-latest
        needs: [fetch]
        strategy:
            matrix:
                side: [left, right]

        steps:
        -   uses: actions/checkout@v4
            with:
                persist-credentials: false
        -   uses: actions/setup-python@v5
            with:
                python-version: '3.13'
        -   uses: yezz123/setup-uv@v4.1
            with:
                uv-venv: .venv
                uv-version: 0.5.25
                uv-cache: true

        -   uses: actions/download-artifact@v4
            with:
                name: issues-dump
                path: downloaded/

        -   name: Get Issue
            id: get-issue
            if: github.event_name == 'issues'
            uses: actions-cool/issues-helper@v3
            with:
                actions: get-issue
                token: ${{ secrets.GITHUB_TOKEN }}

        -   name: Get PR number to check
            id: pr-number
            run: |
                if [ -z "${INPUT_PR}" ]; then
                    pr=$(sed -E 's/.*#([[:digit:]]+).*/\1/g' <<<"${ISSUE_TITLE}")
                    if [ -z "$pr" ]; then
                        echo 'No PR number found' >&2
                        exit 1
                    else
                        echo "pr=${pr}" >> "$GITHUB_OUTPUT"
                    fi
                else
                    echo "pr=${INPUT_PR}" >> "$GITHUB_OUTPUT"
                fi
            env:
                INPUT_PR: ${{ inputs.pr }}
                ISSUE_TITLE: ${{ steps.get-issue.outputs.issue-title }}

        -   name: Apply mypy
            run: |
                uv run run --only-${{ matrix.side }} --pr "${PR}"
            env:
                GH_ACCESS_TOKEN: ${{ secrets.CUSTOM_GITHUB_PAT }}
                PR: ${{ steps.pr-number.outputs.pr }}
                TQDM_MININTERVAL: '5'

        -   uses: actions/upload-artifact@v4
            with:
                name: results-${{ matrix.side }}
                path: outputs/

    diff:
        runs-on: ubuntu-latest
        needs: [apply]
        permissions:
            issues: write

        steps:
        -   uses: actions/checkout@v4
            with:
                persist-credentials: false
        -   uses: actions/setup-python@v5
            with:
                python-version: '3.13'
        -   uses: yezz123/setup-uv@v4.1
            with:
                uv-venv: .venv
                uv-version: 0.5.25
                uv-cache: true

        -   uses: actions/download-artifact@v4
            with:
                name: issues-dump
                path: downloaded/
        -   uses: actions/download-artifact@v4
            with:
                pattern: results-*
                path: outputs/
                merge-multiple: true

        -   name: Compare outputs
            id: compare
            run: |
                uv run diff --no-snippets --diff-originals | tee out.txt
                {
                    echo 'diff-text<<EOF';
                    cat out.txt;
                    echo 'EOF';
                } >> "$GITHUB_OUTPUT"
            env:
                GH_ACCESS_TOKEN: ${{ secrets.CUSTOM_GITHUB_PAT }}

        -   name: Post results
            if: github.event_name == 'issues'
            uses: actions-cool/issues-helper@v3
            with:
                actions: create-comment
                token: ${{ secrets.GITHUB_TOKEN }}
                body: |
                    Results are ready!

                    ${{ steps.compare.outputs.diff-text }}

        -   name: Close issue
            if: github.event_name == 'issues'
            uses: actions-cool/issues-helper@v3
            with:
                actions: close-issue
                token: ${{ secrets.GITHUB_TOKEN }}
                close-reason: completed
