name: Close old issues

on:
    workflow_dispatch:
    schedule:
    -   cron: 40 17 */1 * *

permissions:
    contents: read

jobs:
    sync:
        runs-on: ubuntu-latest
        permissions:
            issues: write
        steps:
        -   name: close-issues
            uses: actions-cool/issues-helper@v3
            with:
                actions: close-issues
                token: ${{ secrets.GITHUB_TOKEN }}
                inactive-day: 14
