name: Lint

on:
  pull_request:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.13'

      - name: install project
        run: |
          uv sync --dev
          uv pip install pip

      - uses: pre-commit/action@v3.0.1
        env:
          GH_TOKEN: ${{ secrets.CUSTOM_GITHUB_PAT }}
