name: Lint

on:
    pull_request:
    push:
        branches: [master]

permissions:
    contents: read

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
            with:
                persist-credentials: false
        -   uses: actions/setup-python@v5
            with:
                python-version: '3.13'
        -   uses: yezz123/setup-uv@v4
            with:
                uv-venv: .venv
        -   name: install project
            run: |
                uv sync --dev
        -   uses: pre-commit/action@v3.0.1
