name: Lint

on:
  pull_request:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - uses: pre-commit/action@v3.0.1
        env:
          GH_TOKEN: ${{ secrets.CUSTOM_GITHUB_PAT }}

  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.13'
      - name: install deps
        run: uv sync --no-install-project --dev
      - name: run mypy
        run: uv run mypy src/mypy_issues/ --config-file pyproject.toml
