name: sync-issues

on:
    workflow_dispatch:
    schedule:
    -   cron: 0 */1 * * *

permissions:
    contents: read

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
            with:
                persist-credentials: false
        -   uses: actions/setup-python@v5
            with:
                python-version: '3.13'
        -   uses: yezz123/setup-uv@v4
            with:
                uv-venv: .venv

        -   uses: actions/cache@v4
            with:
                path: downloaded/
                key: issues-dump-${{ github.run_id }}
                restore-keys: issues-dump-

        -   name: Fetch issues
            run: |
                uv run fetch
            env:
                GH_ACCESS_TOKEN: ${{ secrets.CUSTOM_GITHUB_PAT }}
